theme: minima
title: Kristian is the best at GitHub
author: Kristian Jackson
email: kristian.jackson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: RealKrisJackson # DO NOT include the @ character, or else the build will fail!
github_username:  kristianjackson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
